### ISSUE TITLE
Lifecycle 2.8.0 にするとクラッシュする

### ISSUE THREAD

**Issue by matsumo0922** [matsumo0922/yumemi-codecheck#44]
Lifecycle 2.8.0 と Compose 1.7.0 未満を同時に利用すると以下の例外が出てクラッシュする

```
java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:26)
	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2135)
	at androidx.lifecycle.compose.FlowExtKt.collectAsStateWithLifecycle(FlowExt.kt:182)
	at jp.co.yumemi.android.code_check.app.YacMainActivity$onCreate$1.invoke(YacMainActivity.kt:37)
```

**Comment by matsumo0922** [comment]
仕様らしい
Compose 1.7.0 はまだ beta なんですが...
ひどすぎる

FYI: https://issuetracker.google.com/issues/336842920?pli=1
